/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fptu.prtj311.jtable;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class frmEmployees extends javax.swing.JFrame {

    //khai báo các biến ban đầu
    String fileName = "C:\\Users\\hp\\Desktop\\JAVA DESK\\EmployeeManegement\\src\\fptu\\prtj311\\jtable\\Employees.txt";
    Vector<String> header = new Vector<String>();
    Vector data = new Vector();

    //khai bao 2 bien trang thai cho cac hoat dong them moi va thay doi du lieu
    boolean addNew = false;
    boolean changed = false;

    /**
     * Creates new form frmEmployees
     */
    private void loadData() {
        try {
            //khai bao 1 doi tuong file
            File file = new File(fileName);
            //khai bao 1 doi tuong file reader cho hoat dong doc du lieu tu file
            FileReader fr = new FileReader(file);
            //khai bao 1 doi tuong BufferedReader de doc du lieu vtu Buffe vao chuong trinh
            BufferedReader br = new BufferedReader(fr);
            //tien hanh doc du lieu trong file theo tung dong
            String aDetails;
            while ((aDetails = br.readLine()) != null) {
                StringTokenizer stk = new StringTokenizer(aDetails, ";");
                String code = stk.nextToken();
                String name = stk.nextToken();
                String salary = stk.nextToken();
                //tao 1 vector sau khi doc du lieu tren tung dong
                Vector v = new Vector();
                v.add(code);
                v.add(name);
                v.add(salary);
                //them vector vao data
                data.add(v);
            }
        } catch (FileNotFoundException ex1) {
            JOptionPane.showMessageDialog(this, "File not found!");
        } catch (IOException ex2) {
            JOptionPane.showMessageDialog(this, "Cant read file!");
        }
    }

    public frmEmployees() {
        initComponents();

        //khai bao tieu de cho bang
        header.add("Code");
        header.add("Name");
        header.add("Salary");

        //thực hiện load dữ liệu từ Employees.txt
        loadData();

        DefaultTableModel tableModel;
        tableModel = (DefaultTableModel) tblEmployees.getModel();

        //fill du lieu vao tableModel
        tableModel.setDataVector(data, header);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnSaveToFile = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(250, 100, 0, 0));
        setResizable(false);

        jLabel1.setText("Employees Details");

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        jLabel2.setText("Code:");

        jLabel3.setText("Name:");

        jLabel4.setText("Salary");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        btnNew.setText("New");
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });

        btnSaveToFile.setText("Save To File");
        btnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToFileActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNew)
                                .addGap(99, 99, 99)
                                .addComponent(btnRemove)
                                .addGap(98, 98, 98)
                                .addComponent(btnSaveToFile))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove)
                    .addComponent(btnSaveToFile)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnExit))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        if (JOptionPane.showConfirmDialog(this, "Do you want EXIT?", "Question", JOptionPane.OK_CANCEL_OPTION, JOptionPane.OK_OPTION) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        addNew = true;
        txtCode.setEnabled(true);
        txtCode.setEditable(true);
        txtCode.setText(null);
        txtName.setText(null);
        txtSalary.setText(null);
        txtCode.requestFocus();
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        //kiem tra du lieu tren cac JTextfield da hop le hay chua
        if (!valid()) {
            return;
        }
        if (addNew == true) {
            String code = txtCode.getText().trim();
            String name = txtName.getText().trim();
            String saraly = txtSalary.getText().trim();
            Vector v = new Vector();
            v.add(code);
            v.add(name);
            v.add(saraly);
            data.add(v);
        } else {
            //update lai du lieu cho tblEmployees
        }

        //refresh lai tblEmployees
        tblEmployees.updateUI();
        changed = true;
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
        int pos = this.tblEmployees.getSelectedRow();
        if (pos >= 0) {
            String code = (String) (tblEmployees.getValueAt(pos, 0));
            if (JOptionPane.showConfirmDialog(this, "Delete the " + code + " employee ?") == JOptionPane.OK_OPTION) {
                data.remove(pos);
                tblEmployees.updateUI();
                changed = true;
            }
        }
    }//GEN-LAST:event_btnRemoveMouseClicked

    private void btnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToFileActionPerformed
        try {
            File f = new File(fileName);
            PrintWriter pf = new PrintWriter(f);
            int n = this.tblEmployees.getRowCount();
            for (int i = 0; i < n; i++) {
                Vector<String> v = (Vector<String>) (data.get(i));
                String S = v.get(0) + ";" + v.get(1) + ";" + v.get(2);
                pf.println(S);
            }
            pf.close();
            changed = false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cant save to file");
        }
    }//GEN-LAST:event_btnSaveToFileActionPerformed

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseClicked
        int row = this.tblEmployees.getSelectedRow();
        this.txtCode.setText((String) (tblEmployees.getValueAt(row, 0)));
        this.txtCode.setEditable(false);
        this.txtName.setText((String) (tblEmployees.getValueAt(row, 1)));
        this.txtSalary.setText((String) (tblEmployees.getValueAt(row, 2)));
        addNew = false;
    }//GEN-LAST:event_tblEmployeesMouseClicked

    private void tblEmployeesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeesMouseReleased
        if (this.tblEmployees.isEditing()) {
            int row = tblEmployees.getSelectedRow();
            int column = tblEmployees.getSelectedColumn();
            tblEmployees.getCellEditor(row, column).cancelCellEditing();
        }
    }//GEN-LAST:event_tblEmployeesMouseReleased

    private boolean valid() {
        String s = "";
        if (addNew == true) {
            s = txtCode.getText().trim().toUpperCase();
            txtCode.setText(s);
            //kiem tra code theo dung dinh dang hay chua 
            if (!s.matches("^E\\d{3}$")) {
                JOptionPane.showMessageDialog(this, "Code format: E000");
                return false;
            }
            //kiem tra trung lap cua code
            for (int i = 0; i < data.size(); i++) {
                //lay tung ban ghi trong data theo vi tri
                Vector v = (Vector) data.get(i);
                //so sanh gia tri tren txtCode co trung voi phan tu dau tien trong data 
                if (s.equalsIgnoreCase((String) v.get(0))) {
                    JOptionPane.showMessageDialog(this, "Code duplicated!");
                    txtCode.requestFocus();
                    return false;
                }
            }
            //kiem tra ten khong duoc de trong
            if (txtName.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Name is required");
                return false;
            }

            if (!txtSalary.getText().trim().matches("^\\d+$")) {
                JOptionPane.showMessageDialog(this, "Salary is an interger");
                return false;
            }
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
